### ISSUE TITLE
Not launching anything

### ISSUE THREAD

**Issue by rowbawts** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#53]
This used to work for me but now it doesn't open anything and this is what I see in the console

```
Traceback (most recent call last):
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 1434, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 1223, in init_session
    g_compatdata.setup_prefix()
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 909, in setup_prefix
    try_copy(g_proton.lib64_dir + "vkd3d/libvkd3d-shader-1.dll",
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 125, in try_copy
    shutil.copy(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 426, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/app/share/steam/compatibilitytools.d/Proton-GE/lib/vkd3d/libvkd3d-shader-1.dll'
```

**Comment by juxuanu** [comment]
Same here. Cannot launch anything.
