### ISSUE TITLE
Can't start game

### ISSUE THREAD

**Issue by juxuanu** [flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE#57]
```
Traceback (most recent call last):
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 1442, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 1231, in init_session
    g_compatdata.setup_prefix()
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 911, in setup_prefix
    try_copy(g_proton.lib_dir + "vkd3d/libvkd3d-shader-1.dll",
  File "/app/share/steam/compatibilitytools.d/Proton-GE/proton", line 125, in try_copy
    shutil.copy(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 426, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/app/share/steam/compatibilitytools.d/Proton-GE/lib32/vkd3d/libvkd3d-shader-1.dll'
```
```
╰─🚀 LC_ALL=C flatpak info com.valvesoftware.Steam.CompatibilityTool.Proton-GE

Proton-GE (community build) - Latest Proton-GE version built on the Flatpak
Freedesktop SDK

          ID: com.valvesoftware.Steam.CompatibilityTool.Proton-GE
         Ref: runtime/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.20-GE-1-1
     License: BSD-3-Clause and LGPL-2.1 and zlib-acknowledgement and Zlib and OFL-1.1 and MIT and MPL-2.0 and LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.5?GB

      Commit: 3ab1ff8058b1b84237fb8e5a59f93455856e325745a2a56ae0960bed6801e310
      Parent: e0f5849bd8faa330d1e5a3667062f1bf5a818c497aa7494833400c9c5d6fec93
     Subject: remove vkd3d-32bit module (98b0f92a)
        Date: 2021-11-02 11:36:45 +0000
```

**Comment by podiki** [comment]
Same problem here. Seems to be exactly what this commit did: 871cb434bc7e66d54aacf8b942d1cfd8e2dbdf85

**Comment by Solarinas** [comment]
Having the same problem as well. Reverted to the previous version until we can get a fix

`flatpak update --commit=e0f5849bd8faa330d1e5a3667062f1bf5a818c497aa7494833400c9c5d6fec93 com.valvesoftware.Steam.CompatibilityTool.Proton-GE`

**Comment by gasinvein** [comment]
@Lctrs The `proton` script tries to copy the 32-bit vkd3d dll. This probably needs patching out. If you're going to do this, please use a separate patch file.
